[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Remappings
remappings = [
    "@openzeppelin/contracts/=/Users/adarsh/Documents/social-yield-protocol/contracts/lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=/Users/adarsh/Documents/social-yield-protocol/contracts/lib/openzeppelin-contracts-upgradeable/contracts/",
    "ds-test/=/Users/adarsh/Documents/social-yield-protocol/contracts/lib/forge-std/lib/ds-test/src/",
    "forge-std/=/Users/adarsh/Documents/social-yield-protocol/contracts/lib/forge-std/src/",
    "kaia-contracts/=/Users/adarsh/Documents/social-yield-protocol/contracts/lib/kaia-contracts/",
    "openzeppelin-contracts-upgradeable/=/Users/adarsh/Documents/social-yield-protocol/contracts/lib/openzeppelin-contracts-upgradeable/",
    "openzeppelin-foundry-upgrades/=/Users/adarsh/Documents/social-yield-protocol/contracts/lib/openzeppelin-foundry-upgrades/src/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
